import { useState, useEffect } from "react";
import { Link, useSearch } from "wouter";
import AppShell from "@/components/AppShell";
import ConfidenceBar from "@/components/ConfidenceBar";
import StatusBadge from "@/components/StatusBadge";
import { generateReport } from "@/services/api";
import { Download, ArrowLeft, Sparkles, Loader2 } from "lucide-react";

interface ReportData {
  report_id: string;
  batch_id: string;
  generated_date: string;
  status: string;
  confidence: number;
  severity: string;
  query: string;
  executive_summary: string;
  findings: string[];
  evidence_sources: string[];
  root_cause_analysis: string;
  corrective_actions: string[];
  preventive_actions: string[];
  confidence_assessment: string;
  raw_report: string;
}

function MetaCard({ label, value, isNode }: { label: string; value: string | React.ReactNode; isNode?: boolean }) {
  return (
    <div
      className="rounded-xl flex-1 min-w-28 p-4"
      style={{ background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.08)" }}
    >
      <p className="text-xs text-muted-foreground mb-1">{label}</p>
      {isNode ? value : <p className="text-sm font-semibold text-white">{value}</p>}
    </div>
  );
}

function SectionDivider() {
  return <div className="divider-glow my-6" />;
}

function SectionHeader({ num, title }: { num: number; title: string }) {
  return (
    <div className="flex items-center gap-3 mb-3">
      <span
        className="w-7 h-7 rounded-xl flex items-center justify-center text-xs font-bold flex-shrink-0"
        style={{
          background: "rgba(59,130,246,0.12)",
          color: "#3B82F6",
          border: "1px solid rgba(59,130,246,0.2)",
        }}
      >
        {num}
      </span>
      <h3 className="text-sm font-semibold text-white">{title}</h3>
    </div>
  );
}

export default function Report() {
  const [report, setReport] = useState<ReportData | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [query, setQuery] = useState("");
  const [inputQuery, setInputQuery] = useState("");

  // On mount: auto-load latest investigation from history if available
  useEffect(() => {
    fetch("http://localhost:8000/history")
      .then((r) => r.json())
      .then((data) => {
        const latest = data?.investigations?.[0];
        if (latest?.query) {
          setInputQuery(latest.query);
        }
      })
      .catch(() => {});
  }, []);

  const handleGenerate = async (q: string) => {
    if (!q.trim()) return;
    setLoading(true);
    setError(null);
    setQuery(q.trim());
    try {
      const data = await generateReport({ query: q.trim() });
      if (!data) {
        setError("Backend unavailable. Please ensure the server is running.");
        return;
      }
      setReport(data as ReportData);
    } catch (err: any) {
      setError(err?.response?.data?.detail ?? "Report generation failed. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const handleExport = () => {
    if (!report) {
      window.print();
      return;
    }
    const content = `CellSage AI Investigation Report
Report ID: ${report.report_id}
Batch ID: ${report.batch_id}
Generated: ${report.generated_date}
Confidence: ${report.confidence}%
Severity: ${report.severity}

QUERY
${report.query}

1. EXECUTIVE SUMMARY
${report.executive_summary}

2. INVESTIGATION FINDINGS
${report.findings.map((f, i) => `  ${i + 1}. ${f}`).join("\n")}

3. EVIDENCE SOURCES
${report.evidence_sources.map((e) => `  - ${e}`).join("\n")}

4. ROOT CAUSE ANALYSIS
${report.root_cause_analysis}

5. CORRECTIVE ACTIONS
${report.corrective_actions.map((a, i) => `  ${i + 1}. ${a}`).join("\n")}

6. PREVENTIVE ACTIONS
${report.preventive_actions.map((a, i) => `  ${i + 1}. ${a}`).join("\n")}

7. CONFIDENCE ASSESSMENT
${report.confidence_assessment}

---
Generated by CellSage AI — Agentic Manufacturing Intelligence
`;
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${report.report_id}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <AppShell title="Report" subtitle="Evidence-backed EV battery manufacturing root-cause analysis">
      <div className="p-6">
        {/* Controls */}
        <div className="flex items-center justify-between mb-6">
          <Link
            href="/investigation"
            className="flex items-center gap-2 text-xs text-muted-foreground hover:text-white transition-colors duration-300"
            data-testid="link-back-investigation"
          >
            <ArrowLeft size={13} />
            Back to Investigation
          </Link>
          <button
            className="flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-semibold text-white btn-glow disabled:opacity-50"
            style={{ background: "linear-gradient(135deg, #3B82F6, #2563EB)" }}
            onClick={handleExport}
            disabled={!report}
            data-testid="button-export-report"
          >
            <Download size={14} />
            Export Report
          </button>
        </div>

        {/* Query input */}
        <div
          className="max-w-4xl mx-auto mb-6 p-5 rounded-2xl"
          style={{ background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.08)" }}
        >
          <p className="text-xs text-muted-foreground mb-3 uppercase tracking-wider font-semibold">
            Generate Investigation Report
          </p>
          <div className="flex gap-3">
            <input
              type="text"
              className="flex-1 px-4 py-2.5 rounded-xl text-sm text-white placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-blue-500/40"
              style={{ background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.1)" }}
              placeholder="e.g. Why did Batch EV-1024 fail capacity testing?"
              value={inputQuery}
              onChange={(e) => setInputQuery(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && handleGenerate(inputQuery)}
              data-testid="input-report-query"
            />
            <button
              className="flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-semibold text-white disabled:opacity-50 transition-all"
              style={{ background: "linear-gradient(135deg, #3B82F6, #2563EB)" }}
              onClick={() => handleGenerate(inputQuery)}
              disabled={loading || !inputQuery.trim()}
              data-testid="button-generate-report"
            >
              {loading ? <Loader2 size={14} className="animate-spin" /> : <Sparkles size={14} />}
              {loading ? "Generating..." : "Generate"}
            </button>
          </div>
          {error && (
            <p className="mt-2 text-xs" style={{ color: "#EF4444" }}>
              {error}
            </p>
          )}
        </div>

        {/* Loading state */}
        {loading && (
          <div className="max-w-4xl mx-auto glass-card p-12 flex flex-col items-center justify-center gap-4">
            <Loader2 size={32} className="animate-spin text-blue-400" />
            <p className="text-sm text-muted-foreground">Running investigation pipeline...</p>
            <p className="text-xs text-muted-foreground">Retrieving evidence · Analyzing sensors · Generating root cause</p>
          </div>
        )}

        {/* Empty state */}
        {!loading && !report && (
          <div className="max-w-4xl mx-auto glass-card p-12 flex flex-col items-center justify-center gap-3 text-center">
            <div
              className="w-12 h-12 rounded-xl flex items-center justify-center mb-2"
              style={{ background: "rgba(59,130,246,0.08)", border: "1px solid rgba(59,130,246,0.15)" }}
            >
              <Sparkles size={22} className="text-blue-400" />
            </div>
            <p className="text-sm font-semibold text-white">No report generated yet</p>
            <p className="text-xs text-muted-foreground max-w-sm">
              Enter an investigation query above and click Generate to produce a full AI-powered report.
            </p>
          </div>
        )}

        {/* Report container */}
        {!loading && report && (
          <div
            className="glass-card-strong max-w-4xl mx-auto overflow-hidden"
            style={{ border: "1px solid rgba(255,255,255,0.08)", boxShadow: "0 24px 64px rgba(0,0,0,0.6)" }}
          >
            {/* Report header */}
            <div
              className="px-8 pt-8 pb-6 border-b"
              style={{
                borderColor: "rgba(255,255,255,0.06)",
                background: "linear-gradient(135deg, rgba(255,255,255,0.02) 0%, rgba(59,130,246,0.04) 100%)",
              }}
            >
              <div className="flex items-start justify-between gap-4 mb-5">
                <div>
                  <div className="flex items-center gap-2 mb-2">
                    <Sparkles size={16} className="text-blue-400" />
                    <h1 className="text-xl font-bold text-white">CellSage AI Investigation Report</h1>
                  </div>
                  <p className="text-sm text-muted-foreground">EV Battery Manufacturing Root Cause Analysis</p>
                </div>
                <div className="flex-shrink-0">
                  <StatusBadge value={report.status} type="status" />
                </div>
              </div>

              {/* Metadata */}
              <div className="flex flex-wrap gap-3">
                <MetaCard label="Report ID" value={report.report_id} />
                <MetaCard label="Batch ID" value={report.batch_id} />
                <MetaCard label="Generated Date" value={report.generated_date} />
                <MetaCard
                  label="Severity"
                  value={<StatusBadge value={report.severity} type="severity" />}
                  isNode
                />
                <MetaCard
                  label="Confidence"
                  value={
                    <div className="flex items-center gap-2 pt-0.5">
                      <span
                        className="text-sm font-bold"
                        style={{ color: report.confidence >= 80 ? "#22C55E" : report.confidence >= 60 ? "#F59E0B" : "#EF4444" }}
                      >
                        {report.confidence}%
                      </span>
                    </div>
                  }
                  isNode
                />
              </div>
            </div>

            {/* Report body */}
            <div className="px-8 py-6 space-y-0">
              <div>
                <SectionHeader num={1} title="Executive Summary" />
                <p className="text-sm text-[#94A3B8] leading-relaxed pl-10">{report.executive_summary}</p>
              </div>
              <SectionDivider />

              <div>
                <SectionHeader num={2} title="Investigation Findings" />
                <ul className="space-y-2 pl-10">
                  {report.findings.map((f, i) => (
                    <li key={i} className="flex items-start gap-2 text-sm text-[#94A3B8]">
                      <span
                        className="mt-1.5 w-1.5 h-1.5 rounded-full flex-shrink-0"
                        style={{ background: "#3B82F6", boxShadow: "0 0 6px rgba(59,130,246,0.4)" }}
                      />
                      {f}
                    </li>
                  ))}
                </ul>
              </div>
              <SectionDivider />

              <div>
                <SectionHeader num={3} title="Evidence Sources" />
                <ul className="space-y-2 pl-10">
                  {report.evidence_sources.map((e, i) => {
                    const colonIdx = e.indexOf(":");
                    const label = colonIdx > -1 ? e.slice(0, colonIdx) : e;
                    const rest = colonIdx > -1 ? e.slice(colonIdx) : "";
                    return (
                      <li key={i} className="flex items-start gap-2 text-sm text-[#94A3B8]">
                        <span
                          className="mt-1.5 w-1.5 h-1.5 rounded-full flex-shrink-0"
                          style={{ background: "#A78BFA", boxShadow: "0 0 6px rgba(167,139,250,0.4)" }}
                        />
                        <span>
                          <span className="font-semibold text-white">{label}</span>
                          {rest}
                        </span>
                      </li>
                    );
                  })}
                </ul>
              </div>
              <SectionDivider />

              <div>
                <SectionHeader num={4} title="Root Cause Analysis" />
                <p className="text-sm text-[#94A3B8] leading-relaxed pl-10">{report.root_cause_analysis}</p>
              </div>
              <SectionDivider />

              <div>
                <SectionHeader num={5} title="Corrective Actions" />
                <ul className="space-y-2 pl-10">
                  {report.corrective_actions.map((a, i) => (
                    <li key={i} className="flex items-start gap-2.5 text-sm text-[#94A3B8]">
                      <span
                        className="mt-0.5 w-5 h-5 rounded-full flex-shrink-0 flex items-center justify-center text-xs font-bold"
                        style={{
                          background: "rgba(239,68,68,0.10)",
                          color: "#EF4444",
                          border: "1px solid rgba(239,68,68,0.2)",
                        }}
                      >
                        {i + 1}
                      </span>
                      {a}
                    </li>
                  ))}
                </ul>
              </div>
              <SectionDivider />

              <div>
                <SectionHeader num={6} title="Preventive Actions" />
                <ul className="space-y-2 pl-10">
                  {report.preventive_actions.map((a, i) => (
                    <li key={i} className="flex items-start gap-2.5 text-sm text-[#94A3B8]">
                      <span
                        className="mt-0.5 w-5 h-5 rounded-full flex-shrink-0 flex items-center justify-center text-xs font-bold"
                        style={{
                          background: "rgba(34,197,94,0.10)",
                          color: "#22C55E",
                          border: "1px solid rgba(34,197,94,0.2)",
                        }}
                      >
                        {i + 1}
                      </span>
                      {a}
                    </li>
                  ))}
                </ul>
              </div>
              <SectionDivider />

              <div>
                <SectionHeader num={7} title="Confidence Assessment" />
                <div className="pl-10">
                  <p className="text-sm text-[#94A3B8] leading-relaxed mb-4">{report.confidence_assessment}</p>
                  <div className="max-w-sm">
                    <div className="flex items-center justify-between mb-2">
                      <span className="text-xs text-muted-foreground">Overall Confidence</span>
                      <span
                        className="text-xs font-bold"
                        style={{ color: report.confidence >= 80 ? "#22C55E" : report.confidence >= 60 ? "#F59E0B" : "#EF4444" }}
                      >
                        {report.confidence}%
                      </span>
                    </div>
                    <ConfidenceBar value={report.confidence} showLabel={false} height={8} />
                  </div>
                </div>
              </div>
              <SectionDivider />

              <div className="flex items-center justify-between pt-2 pb-2">
                <p className="text-xs text-muted-foreground">
                  Generated by CellSage AI — Agentic Manufacturing Intelligence
                </p>
                <p className="text-xs text-muted-foreground">{report.generated_date}</p>
              </div>
            </div>
          </div>
        )}
      </div>
    </AppShell>
  );
}