"""Agent 5: Report Agent — create investigation summary reports."""

from datetime import datetime

from agents.state import InvestigationState


def report_agent(state: InvestigationState) -> InvestigationState:
    query = state.get("query", "")
    root_cause = state.get("root_cause", "Not determined")
    confidence = state.get("confidence", "N/A")
    evidence = state.get("evidence", [])
    recommendations = state.get("recommendations", [])
    sensor_analysis = state.get("sensor_analysis", {})

    evidence_lines = "\n".join(f"  - {e}" for e in evidence) or "  - No evidence collected"
    rec_lines = "\n".join(f"  {i}. {r}" for i, r in enumerate(recommendations, 1)) or "  1. No recommendations generated"

    anomalies = sensor_analysis.get("anomalies", [])
    anomaly_lines = (
        "\n".join(
            f"  - {a['parameter']}: {a['value']} (violates {a['sop_violation']})"
            for a in anomalies
        )
        or "  - No sensor anomalies detected"
    )

    report = f"""# CellSage AI Investigation Report

**Generated:** {datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")}

## Investigation Query
{query}

## Root Cause Analysis
{root_cause}

**Confidence:** {confidence}

## Sensor Analysis
{anomaly_lines}

## Evidence
{evidence_lines}

## Recommended Corrective Actions
{rec_lines}

---
*Report generated by CellSage AI — EV Battery Manufacturing Root Cause Analysis Copilot*
"""

    return {**state, "report": report}
